# Generated by Django 6.0.4 on 2026-04-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Summary'),
        ),
    ]
