# Generated by Django 6.0.4 on 2026-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.CharField(max_length=400, verbose_name='Link photo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name of News'),
        ),
    ]
